### ISSUE TITLE
Unecessary creation of a new file for components

### ISSUE THREAD

**Issue by joserigel** [19ec94/interactive-3d-web-design#2]
https://github.com/19ec94/interactive-3d-web-design/blob/acda9ea99a7a92a18ef5a6e34ce6b1eda9e37d16/src/components/PasswordIdent.jsx#L1-L17

Codes like this should be combined with the routed component/page, there is no need to create a separate file for just another react function. Separating files should be reserved for shared components (Components used on multiple pages), especially when the line count is quite low

**Comment by 19ec94** [comment]
I concur. A framework for validating user inputs (including password) has already been proposed in my PR: #1 . 
I am waiting for one of you --  @joserigel, @AlkhazovAvdalim  -- to review the PR.

**Comment by 19ec94** [comment]
This file is no longer used in the code. So, I close this issue for now. Feel free to open if you face any issue with this.
